# -*- coding: utf-8 -*-
# Generated by Django 1.11.15 on 2018-08-07 10:26
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('image_labelling_tool', '0003_auto_20180210_1000'),
    ]

    operations = [
        migrations.CreateModel(
            name='ImageWithLabels',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(blank=True, upload_to='')),
                ('labels', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='image', to='image_labelling_tool.Labels')),
            ],
        ),
    ]
